version: "3.8"
services:
  backend:
    build: ./backend
    container_name: myapp_backend
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - webnet

  frontend:
    build: ./frontend
    container_name: myapp_frontend
    restart: always
    networks:
      - webnet

  nginx:
    image: nginx:stable-alpine
    container_name: myapp_nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/www/certbot:/var/www/certbot  # for Let's Encrypt challenge
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
